name: Build Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -buildmode=plugin -o dist/plugin.so src/plugin.go

      - name: Upload dist
        uses: EndBug/add-and-commit@v7
        with:
          author_name: MacCleanup
          author_email: mac-cleanup@wartner.io
          message: 'Added new binary'
          add: '*.so'
